package com.bluelab.unitenum;

public enum ConversionEnum {
    CELSIUS_TO_FAHRENHEIT,
    CELSIUS_TO_KELVIN,
    FAHRENHEIT_TO_CELSIUS,
    FAHRENHEIT_TO_KELVIN,
    KELVIN_TO_CELSIUS,
    KELVIN_TO_FAHRENHEIT,
    GALLON_TO_LITRE,
    GALLON_TO_MILLILITRE,
    LITRE_TO_GALLON,
    LITRE_TO_MILLILITRE,
    MILLILITRE_TO_GALLON,
    MILLILITRE_TO_LITRE
}
